Handlebar templates
breakfireaus/Inter-book pull request #26
Opened 2022-11-21 07:16 UTC by asish-dewan

Added Sign In and Register Page.
Sign in and Sign Out scripts.

2022-11-21 07:26 UTC, breakfireaus requested changes
please close your #if  handlebar not closed on line 42 main.handlebars

2022-11-21 07:33 UTC, breakfireaus requested changes

2022-11-21 07:33 UTC, breakfireaus commented on views/layouts/main.handlebars
> +
need to close the if

2022-11-21 07:45 UTC, asish-dewan commented on views/layouts/main.handlebars
> +
Done.

2022-11-21 09:30 UTC, Auralise approved these changes
Looks good to me, this is a good start, we will need to possibly restructure as we increase the complete

2022-11-21 16:18 UTC, asish-dewan commented
Added Dashboard + booking templates.

2022-11-22 01:14 UTC, breakfireaus approved these changes
looks good

2022-11-22 01:14 UTC, merged