Seeds
breakfireaus/Inter-book pull request #33
Opened 2022-11-23 11:53 UTC by breakfireaus

2022-11-23 11:54 UTC, breakfireaus commented
will be working on seeds tomorrow between 5 and 6:30 seeds should be completed, something unexpected just happened

2022-11-24 00:03 UTC, Auralise commented
No problems. I will wait to review/approve until the work has continued.

2022-11-24 00:35 UTC, breakfireaus commented
Can you please advise how to put date and time in for seeds date for service start and end @Auralise

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Auralise ***@***.***>
Sent: Thursday, November 24, 2022 11:04:04 AM
To: breakfireaus/Inter-book ***@***.***>
Cc: Matthew Younger-Chudnovsky ***@***.***>; Author ***@***.***>
Subject: Re: [breakfireaus/Inter-book] Seeds (PR #33)


No problems. I will wait to review/approve until the work has continued.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbreakfireaus%2FInter-book%2Fpull%2F33%23issuecomment-1325784756&data=05%7C01%7C%7Cd96a80fa63224a1bfb5808dacdaf66a6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638048450476766339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Je0w5TfY366JzXB6c7wkxQJglUIt%2FRnxC4BMT3nHcB0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZ5SEYVX2E3LAPYW2TJXBHTWJ2WHJANCNFSM6AAAAAASI4CK6Q&data=05%7C01%7C%7Cd96a80fa63224a1bfb5808dacdaf66a6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638048450476766339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RYr5bI6P%2FRBFEjZWxzaMXFjxAsEZ5WPRSyS9nfvRx%2Bg%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-11-24 01:29 UTC, Auralise commented
I assume that it is the ISO standard which would be implemented in the mysql database. Id recommend checking out docs on this: https://www.w3schools.com/sql/sql_dates.asp

The Sequelize DataType.DATE maps to the datetime format in SQL. 

Frankly, I've never done it with sequelize so just play with it until it works

2022-11-24 01:38 UTC, breakfireaus commented
So if I put the format as it is in w3schools it should be fine?



Sent from my Galaxy



-------- Original message --------
From: Auralise ***@***.***>
Date: 24/11/22 12:29 pm (GMT+10:00)
To: breakfireaus/Inter-book ***@***.***>
Cc: Matthew Younger-Chudnovsky ***@***.***>, Author ***@***.***>
Subject: Re: [breakfireaus/Inter-book] Seeds (PR #33)


I assume that it is the ISO standard which would be implemented in the mysql database. Id recommend checking out docs on this: https://www.w3schools.com/sql/sql_dates.asp<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.w3schools.com%2Fsql%2Fsql_dates.asp&data=05%7C01%7C%7Cfef9e92c06b44228dca308dacdbb4f61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638048501641526969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bPHcD2BGP3XvKFiELn8Q6Jo5bjsul5oO1PbEnZhTRYk%3D&reserved=0>

The Sequelize DataType.DATE maps to the datetime format in SQL.

Frankly, I've never done it with sequelize so just play with it until it works

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbreakfireaus%2FInter-book%2Fpull%2F33%23issuecomment-1325835267&data=05%7C01%7C%7Cfef9e92c06b44228dca308dacdbb4f61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638048501641526969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ogb067ht7KB9UtTzNiYb3NKq4D5jmrCHldUEeyT2P3k%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZ5SEYT6CHAQZP2U6DNXX6LWJ3AG7ANCNFSM6AAAAAASI4CK6Q&data=05%7C01%7C%7Cfef9e92c06b44228dca308dacdbb4f61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638048501641526969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZCC61ElErIM0vE7T8U7zNKF1QyHqlwSmUTlkn1P%2ByBM%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-11-24 01:40 UTC, Auralise commented
I don't know, its seemingly a good starting point. I'd just try it and if it does work, play with it and then just test it until it works

2022-11-24 01:46 UTC, breakfireaus commented
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Auralise ***@***.***>
Sent: Thursday, November 24, 2022 12:40:29 PM
To: breakfireaus/Inter-book ***@***.***>
Cc: Matthew Younger-Chudnovsky ***@***.***>; Author ***@***.***>
Subject: Re: [breakfireaus/Inter-book] Seeds (PR #33)


I don't know, its seemingly a good starting point. I'd just try it and if it does work, play with it and then just test it until it works

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbreakfireaus%2FInter-book%2Fpull%2F33%23issuecomment-1325841239&data=05%7C01%7C%7Ce36770f24a5541715ab608dacdbcdeb6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638048508366767427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yllzr2vCP9cFv40JyJaKzg4LUy9ifwSV3%2Bz533SHNa0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZ5SEYT3MSMC6NFPTJWZMBDWJ3BQ3ANCNFSM6AAAAAASI4CK6Q&data=05%7C01%7C%7Ce36770f24a5541715ab608dacdbcdeb6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638048508366767427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W%2F6p%2B7dgJlQa%2BOj%2BQda5zqJ0OV9kls6yU878Wk577vc%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-11-25 01:25 UTC, Auralise requested changes
Matt, please be sure to test these things before submitting them for review by simply running them with the debugger. The assumption will be, especially in the professional world, that code submitted for review has been tested and is working, at least for you and is at the stage where it is working in the larger context of the application. 

Granted this can be a bit different at the start of the project where not everything has been put in place to actually test within context of the application and frankly, we have done our project a bit backwards in this regard but as we have the sequelize models, we can actually test this against them to verify that they work. 

Please review the changes I have proposed and perform some testing of your own to verify that all of these seed files successfully insert into the database before requesting the next review. 

Thanks mate!

2022-11-25 01:25 UTC, Auralise commented on seeds/industry.js
> +    Industry: 'Dance',
```suggestion
    industry: 'Dance',
```

2022-11-25 01:25 UTC, Auralise commented on seeds/industry.js
> +    Industry: 'Construction',
```suggestion
    industry: 'Construction',
```

2022-11-25 01:25 UTC, Auralise commented on seeds/industry.js
> +    Industry: 'IT',
```suggestion
    industry: 'IT',
```

2022-11-25 01:25 UTC, Auralise commented on seeds/industry.js
> +    Industry: 'Fitness',
```suggestion
    industry: 'Fitness',
```

2022-11-25 01:25 UTC, Auralise commented on seeds/industry.js
> +    Industry: 'Law',
```suggestion
    industry: 'Law',
```

2022-11-25 01:25 UTC, Auralise commented on seeds/service.js
> +    start: '2022-12-05T12:00:000Z',
These dates did not insert into the database successfully, producing the following error: 
![image](https://user-images.githubusercontent.com/9697002/203881247-4d674956-c502-4f07-87b7-a7ce5037e372.png)


As discussed, can you please experiment with datetime formats as specified for mysql and described on w3schools here: https://www.w3schools.com/sql/sql_dates.asp

Please test these next time before submitting for the next review as discussed.

2022-11-25 01:25 UTC, Auralise commented on seeds/userIndustry.js
> +        industry_id: 6
```suggestion
        industry_id: 4 
```

This is an invalid industry ID of 6 as we have only defined the seeds for 5 industries.

2022-11-25 10:39 UTC, breakfireaus commented
@Auralise @asish-dewan all fixed

2022-11-25 23:04 UTC, Auralise approved these changes
I have tested the seeds and the database seems to be in the correct state after running the seed. Good job! 

I will merge this in now.

2022-11-25 23:04 UTC, merged